# Generated by Django 5.2.17 on 2026-09-03 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_assetcategory_asset_assetliability_assetvaluehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingsgoal',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='savings_goals', to='finance.account'),
        ),
    ]
